plugins:
  discourse_homepage_filter_enabled:
    default: true
    client: true
  discourse_homepage_filter_groups:
    default: "12"
    type: group_list
    client: false
    allow_any: false
    refresh: true
